language: bash

git:
  depth: 1

before_script:
  - wget https://svn.reactos.org/amine/RosBEBinFull.tar.gz -O RosBE.tar.gz
  - tar -xzf RosBE.tar.gz
  - echo 'cd ../Build && $TRAVIS_BUILD_DIR/configure.sh -DENABLE_ROSTESTS=1 && cd reactos && ninja -k 0 && ninja bootcd' > tmp_file

script:
  - ./RosBEBinFull/RosBE.sh < tmp_file

cache:
  directories:
  - Build
